/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminAddHotDrinkRouteImport } from './routes/admin-add-hot-drink'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as MenuDrinksHotCoffeeRouteImport } from './routes/menu/drinks/hot-coffee'
import { Route as MenuDrinksDrinkIdRouteImport } from './routes/menu/drinks/$drinkId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddHotDrinkRoute = AdminAddHotDrinkRouteImport.update({
  id: '/admin-add-hot-drink',
  path: '/admin-add-hot-drink',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuDrinksHotCoffeeRoute = MenuDrinksHotCoffeeRouteImport.update({
  id: '/menu/drinks/hot-coffee',
  path: '/menu/drinks/hot-coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuDrinksDrinkIdRoute = MenuDrinksDrinkIdRouteImport.update({
  id: '/menu/drinks/$drinkId',
  path: '/menu/drinks/$drinkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-add-hot-drink': typeof AdminAddHotDrinkRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/menu': typeof MenuIndexRoute
  '/menu/drinks/$drinkId': typeof MenuDrinksDrinkIdRoute
  '/menu/drinks/hot-coffee': typeof MenuDrinksHotCoffeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-add-hot-drink': typeof AdminAddHotDrinkRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/menu': typeof MenuIndexRoute
  '/menu/drinks/$drinkId': typeof MenuDrinksDrinkIdRoute
  '/menu/drinks/hot-coffee': typeof MenuDrinksHotCoffeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-add-hot-drink': typeof AdminAddHotDrinkRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/menu/': typeof MenuIndexRoute
  '/menu/drinks/$drinkId': typeof MenuDrinksDrinkIdRoute
  '/menu/drinks/hot-coffee': typeof MenuDrinksHotCoffeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-add-hot-drink'
    | '/sign-in'
    | '/sign-up'
    | '/menu'
    | '/menu/drinks/$drinkId'
    | '/menu/drinks/hot-coffee'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-add-hot-drink'
    | '/sign-in'
    | '/sign-up'
    | '/menu'
    | '/menu/drinks/$drinkId'
    | '/menu/drinks/hot-coffee'
  id:
    | '__root__'
    | '/'
    | '/admin-add-hot-drink'
    | '/sign-in'
    | '/sign-up'
    | '/menu/'
    | '/menu/drinks/$drinkId'
    | '/menu/drinks/hot-coffee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAddHotDrinkRoute: typeof AdminAddHotDrinkRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenuDrinksDrinkIdRoute: typeof MenuDrinksDrinkIdRoute
  MenuDrinksHotCoffeeRoute: typeof MenuDrinksHotCoffeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-add-hot-drink': {
      id: '/admin-add-hot-drink'
      path: '/admin-add-hot-drink'
      fullPath: '/admin-add-hot-drink'
      preLoaderRoute: typeof AdminAddHotDrinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/drinks/hot-coffee': {
      id: '/menu/drinks/hot-coffee'
      path: '/menu/drinks/hot-coffee'
      fullPath: '/menu/drinks/hot-coffee'
      preLoaderRoute: typeof MenuDrinksHotCoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/drinks/$drinkId': {
      id: '/menu/drinks/$drinkId'
      path: '/menu/drinks/$drinkId'
      fullPath: '/menu/drinks/$drinkId'
      preLoaderRoute: typeof MenuDrinksDrinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAddHotDrinkRoute: AdminAddHotDrinkRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenuDrinksDrinkIdRoute: MenuDrinksDrinkIdRoute,
  MenuDrinksHotCoffeeRoute: MenuDrinksHotCoffeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
